graph TD

  subgraph HTMLPages [HTML Pages]
    Projects[projects.html]
  end

  subgraph JavaScript [JavaScript]
    ProjectList[projectListLoader.js]
    SketchfabEmbed[embedSketchfab.js]
    ProjectSteps[projectStepsData.js]
    ProjectLinks[projectLinksLoader.js]
    Carousel[carousel.js]
    ModalZoom[modalZoom.js]
    Init[init.js]
  end

  subgraph JSONData [JSON Data]
    ProjectListData[projectListData.js]
    SketchfabModels[sketchfabModels.js]
    ProjectStepsData[projectSteps.js]
    ProjectLinksData[projectLinks.js]
    CarouselData[carouselData.js]
  end

  Projects --> ProjectList
  Projects --> GithubApp
  Projects --> SketchfabEmbed
  Projects --> ProjectSteps
  Projects --> ProjectLinks
  Projects --> Carousel
  Projects --> ModalZoom
  Projects --> Init
  ProjectList --> ProjectListData
  SketchfabEmbed --> SketchfabModels
  ProjectSteps --> ProjectStepsData
  ProjectLinks --> ProjectLinksData
  Carousel --> CarouselData
  class Projects primary
  class ProjectList secondary
  class SketchfabEmbed secondary
  class ProjectSteps secondary
  class ProjectLinks secondary
  class Carousel secondary
  class ModalZoom secondary
  class Init secondary
  class ProjectListData tertiary
  class SketchfabModels tertiary
  class ProjectStepsData tertiary
  class ProjectLinksData tertiary
  class CarouselData tertiary