graph TD

  subgraph HTMLPages [HTML Pages]
    Index[Index.html]
    ModelBuilder[Model-Builder.html]
    Groupings[Groupings.html]
    SubGroupAnalysis[Sub-Group-Analysis.html]
    GroupAnalysis[Group-Analysis.html]
    FactorAnalysis[Factor-Analysis.html]
  end

  subgraph JavaScript [JavaScript]
    intThematicAnalysis[intThematicAnalysis.js]
    intGroupings[intGroupings.js]
    intSubGroupAnalysis[intSubGroupAnalysis.js]
    intGroupAnalysis[intGroupAnalysis.js]
    intFactorAnalysis[intFactorAnalysis.js]
    intModelBuilder[intModelBuilder.js]
    RiskMatrix[RiskMatrix.js]
  end

  subgraph JSONData [JSON Data]
    thematic_analysisJSON[thematic_analysisJSON.js]
    risk_matrixJSON[risk_matrixJSON.js]
  end

  Index --> intThematicAnalysis
  intThematicAnalysis --> thematic_analysisJSON
  Groupings --> intGroupings
  intGroupings --> thematic_analysisJSON
  SubGroupAnalysis --> intSubGroupAnalysis
  intSubGroupAnalysis --> thematic_analysisJSON
  GroupAnalysis --> intGroupAnalysis
  intGroupAnalysis --> thematic_analysisJSON
  FactorAnalysis --> intFactorAnalysis
  intFactorAnalysis --> thematic_analysisJSON
  ModelBuilder --> intModelBuilder
  intModelBuilder --> thematic_analysisJSON
  RiskMatrix --> risk_matrixJSON
  style Index fill:#cfe2f3,stroke:#036
  style ModelBuilder fill:#fce5cd,stroke:#a61c00
  style Groupings fill:#fce5cd,stroke:#a61c00
  style SubGroupAnalysis fill:#fce5cd,stroke:#a61c00
  style GroupAnalysis fill:#fce5cd,stroke:#a61c00
  style FactorAnalysis fill:#fce5cd,stroke:#a61c00
  style intThematicAnalysis fill:#fff2cc,stroke:#cc9900
  style intModelBuilder fill:#fff2cc,stroke:#cc9900
  style intGroupings fill:#fff2cc,stroke:#cc9900
  style intSubGroupAnalysis fill:#fff2cc,stroke:#cc9900
  style intGroupAnalysis fill:#fff2cc,stroke:#cc9900
  style intFactorAnalysis fill:#fff2cc,stroke:#cc9900
  style RiskMatrix fill:#e6f7ff,stroke:#005c99
  style thematic_analysisJSON fill:#f9cb9c,stroke:#783f04
  style risk_matrixJSON fill:#f9cb9c,stroke:#783f04