erDiagram

    User {
        user_id
        name
        email
    }
    Post {
        post_id
        user_id
        content
    }
    Comment {
        comment_id
        post_id
        user_id
        content
    }
  User ||--o{ Post : one-to-many }
  Post ||--o{ Comment : one-to-many }
  User ||--o{ Comment : one-to-many }